### ISSUE TITLE
_no_self=False broken ?

### ISSUE THREAD

**Issue by trecouvr** [arskom/spyne#371]
Hi,

I tried to set the `_no_self` argument to `False` and I got the following error when I tried to interact with the server:

```
Traceback (most recent call last):
  File "/Users/thomas/dev/spyne/spyne/application.py", line 144, in process_request
    ctx.out_object = self.call_wrapper(ctx)
  File "/Users/thomas/dev/spyne/spyne/application.py", line 205, in call_wrapper
    if cls.__orig__ is not None:
AttributeError: 'NoneType' object has no attribute '__orig__'
```

Here is the service definition:

``` python
class A(ServiceBase):
    @rpc(String, _returns=String, _no_self=False)
    def hello(self, ctx, name):
        print self, ctx, name
        return 'Hello, %s' % name
```

**Comment by chrislawlor** [comment]
Please work on this documentation. I'm having a similar issue, no docs since spyne 1.10 (the docs mention 1.11, but mostly refer to 1.10), so I using the code as documentation, which contains:

```
    :param _no_self: This method does not get an implicit 'self' argument
        (before any other argument, including ctx).
```

and, a little later:

```
_no_self = kparams.pop('_no_self', True)
```

This leads one to believe that I can pass `_no_self=False` to my `rpc` decorator, and have a reference to my `ServiceBase` subclass.


But now your comment earlier  completely changes that assumption:

> Which class? A? A is never instantiated. What are you trying to accomplish?

My `ServiceBase` subclass is never instantiated? That's not exactly behavior I'd expect.

As to what I'm trying to accomplish, I need to publish a new version of our SOAP service. I'd intended on doing that by subclassing our existing `ServiceBase` subclass, overwriting the endpoints that changed, and moving common functionality into other methods. Something like this:


```
class MyService(ServiceBase):
    def _get_status(self, obj_id):
        status = # the code to get the status
        return status

    @rpc(M(Integer), _returns=StatusResponse, _no_self=False)
    def get_status(self, ctx, obj_id):
        return StatusResponse(status=self._get_status(obj_id))

class MyServiceV2(MyService):
    @rpc(M(Integer), _returns=StatusResponseV2, _no_self=False)
    def get_status(self, ctx, obj_id):
        return StatusResponseV2(status=self.get_status(obj_id))
```

If that isn't possible, or the recommended way to support multiple versions of a service, can you point me in the right direction? Your link http://lists.spyne.io/listinfo/people is broken.

**Comment by plq** [comment]
Thanks for the heads-up, I fixed the ml interface.

see: https://lists.spyne.io/archives/people/2014-June/000056.html

**Comment by chrislawlor** [comment]
@plq thank you, appreciate the fix and the link!
