### ISSUE TITLE
Packaging issue for spyne 2.13.4a0

### ISSUE THREAD

**Issue by eclar** [arskom/spyne#594]
Spyne 2.13.4a0 has been released as 2.13.4a1 on pypi. The content of the package is 2.13.4a0 but the package name indicates the 2.13.4a1 version.

Step to reproduce:
``` console
$ pip install spyne==2.13.4a0
Collecting spyne==2.13.4a0
 Could not find a version that satisfies the requirement spyne==2.13.4a0 (from versions: 2.8.0rc0, 2.8.1rc0, 2.8.2rc0, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 2.10.8, 2.10.9, 2.10.10, 2.11.0, 2.12.9, 2.12.10, 2.12.11, 2.12.12, 2.12.13, 2.12.14, 2.12.15, 2.12.16, 2.13.1a0, 2.13.2a0, 2.13.3a0, 2.13.4a1)
No matching distribution found for spyne==2.13.4a0
```
Wherease:
``` console
$ pip install spyne==2.13.4a1 --quiet && pip show spyne
 Requested spyne==2.13.4a1 from https://files.pythonhosted.org/packages/fb/93/8a48a2a71c279d7f7bcf0ecd78ecdd6e99f10c1ad9b20c503889d2a1ff70/spyne-2.13.4a1.tar.gz#sha256=1f4c8794c15d32b6d749d3a30d64583e2550ab4bdaf388cf414df1b16de69395, but installing version 2.13.4a0
Name: spyne
Version: 2.13.4a0
Summary: A transport and architecture agnostic rpc library that focuses on exposing public services with a well-defined API.
Home-page: http://spyne.io
Author: Burak Arslan
Author-email: burak+package@spyne.io
License: LGPL-2.1
Location: /venv/lib/python3.6/site-packages
Requires: pytz
Required-by: 
```

**Comment by plq** [comment]
The package name is spyne-2.13.4-alpha, not spyne-2.13.4a0 nor spyne-2.13.4a1. I don't control how pip mangles my versions. It at least used to be consistent so maybe take this to the pip guys?.

FYI: http://spyne.io/docs/2.11/history.html#versioning

**Comment by xavfernandez** [comment]
The version is "mangled" according to [PEP 440](https://www.python.org/dev/peps/pep-0440/).
```
In [1]: from packaging.version import parse
In [2]: parse('2.13.4-alpha')
Out[2]: <Version('2.13.4a0')>
```

It's however unclear how [spyne-2.13.4a1.tar.gz](https://files.pythonhosted.org/packages/fb/93/8a48a2a71c279d7f7bcf0ecd78ecdd6e99f10c1ad9b20c503889d2a1ff70/spyne-2.13.4a1.tar.gz) file from PyPI ended up containing a `spyne-2.13.4a0.tar` file, itself containing a `2.13.4a0` release.
This is the main issue and since it did not happen in previous alpha releases something must have changed during the last release (maybe `setuptools` version ?).

In the meantime, you could perhaps re-upload a `spyne-2.13.4a0.tar.gz` containing the same thing as the current `spyne-2.13.4a1.tar.gz`.
